spring:
  mail:
    host: smtp.gmail.com
    username: abclsdjf23@gmail.com
    password: zdtc tmch sutw ejkb
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true